spring.application.name=authsystem

spring.datasource.url=jdbc:mysql://localhost:3306/auth_security_db
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=ThisIsMySecretKeyForJwtTokenGenerationThisIsMySecretKey
jwt.expiration=3600000

server.port=8080